language: python
python: 3.6

env:
  global:
    - S3_BUCKET_PREFIX="${S3_BUCKET}/${TRAVIS_BRANCH}/assets"

install: pip install awscli

script:
  # list installer directory (from https://stackoverflow.com/questions/1767384/ls-command-how-can-i-get-a-recursive-full-path-listing-one-line-per-file)
  - ls -R installer | awk '/:$/&&f{s=$0;f=0}/:$/&&!f{sub(/:$/,"");s=$0;f=1;next}NF&&f{ print s"/"$0 }'

deploy:
  - provider: script
    script: aws s3 sync --delete src/ s3://${S3_BUCKET_PREFIX}
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master|develop|staging$
